// Generated by CoffeeScript 1.6.3
var icecreamModel, ok, selectionModel, testModels, updateIcecreamList, updateSelection;

icecreamModel = {
  list: [
    {
      id: 't1',
      name: "バニラ"
    }, {
      id: 't2',
      name: "チョコレートチップ"
    }, {
      id: 't3',
      name: "オレンジシャーベット"
    }, {
      id: 't4',
      name: "チョコミント"
    }, {
      id: 't5',
      name: "ストロベリー"
    }, {
      id: 't6',
      name: "抹茶"
    }
  ],
  getAll: function() {
    return this.list;
  },
  findById: function(id) {
    return $.grep(this.list, function(val) {
      return id === val.id;
    })[0];
  }
};

selectionModel = {
  list: [],
  icecreamNumber: 2,
  add: function(item) {
    var list;
    list = this.list;
    list.push(item);
    if (list.length > this.icecreamNumber) {
      list.shift();
    }
    return this.updateView();
  },
  contain: function(icecream) {
    return this.list.indexOf(icecream) >= 0;
  },
  containById: function(id) {
    return this.contain(icecreamModel.findById(id));
  },
  getIcecreams: function() {
    return this.list;
  },
  updateView: function() {
    updateSelection();
    return updateIcecreamList();
  }
};

updateSelection = function() {
  $('#icecreams input[type="checkbox"]').each(function(i, elm) {
    return elm.checked = selectionModel.containById(elm.name);
  });
};

updateIcecreamList = function() {
  $("#icecream-list").text($.map(selectionModel.getIcecreams(), function(val) {
    return val.name;
  }).join(" > "));
};

ok = function(title, expect, value) {
  if (expect === value) {
    return console.log("OK : " + title);
  } else {
    return console.log("NG : " + title + " [" + expect + "] --> [" + value + "]");
  }
};

testModels = function() {
  var all;
  all = icecreamModel.getAll();
  ok("icecreamModel:個数", all.length, 6);
  ok("icecreamModel.findById", icecreamModel.findById("t4"), all[3]);
  ok("selectionModel:最初の個数", selectionModel.getIcecreams().length, 0);
  ok("selectionModelcontain:空の場合", false, selectionModel.contain(all[0]));
  selectionModel.add(all[0]);
  ok("selectionModel.contain:1つめを追加した時の個数", selectionModel.getIcecreams().length, 1);
  ok("selectionModel.contain:1つめを追加した時のチェック", true, selectionModel.contain(all[0]));
  selectionModel.add(all[1]);
  ok("selectionModel.contain:2つめを追加した時の個数", selectionModel.getIcecreams().length, 2);
  ok("selectionModel.contain:2つめを追加した時のチェック", true, selectionModel.contain(all[1]));
  selectionModel.add(all[2]);
  ok("selectionModel:3つめを追加した場合の", selectionModel.getIcecreams().length, 2);
  ok("selectionModel.contain:3つめを追加した時のチェック", true, selectionModel.contain(all[2]));
  return ok("selectionModel.contain:3つめを追加した時の個数", false, selectionModel.contain(all[0]));
};

testModels();

$(function() {
  var els;
  els = $('#icecreams');
  $.each(icecreamModel.getAll(), function(i, icecream) {
    els.append($("<li>").append($("<input type='checkbox'>").attr('name', icecream.id)).append($("<span>").text(icecream.name)).click(function() {}));
  });
  return selectionModel.updateViews;
});
