// Generated by CoffeeScript 1.6.3
/*
  Model
*/

var iceModel, ok, onclickIce, selectionModel, testModels, updateIceList, updateSelection;

iceModel = {
  list: [
    {
      id: 't1',
      name: "バニラ"
    }, {
      id: 't2',
      name: "チョコレートチップ"
    }, {
      id: 't3',
      name: "オレンジシャーベット"
    }, {
      id: 't4',
      name: "チョコミント"
    }, {
      id: 't5',
      name: "ストロベリー"
    }, {
      id: 't6',
      name: "抹茶"
    }
  ],
  getAll: function() {
    return this.list;
  },
  findById: function(id) {
    return $.grep(this.list, function(val) {
      return id === val.id;
    })[0];
  }
};

selectionModel = {
  list: [],
  numberOfStage: 2,
  add: function(item) {
    var list;
    list = this.list;
    list.push(item);
    if (list.length > this.numberOfStage) {
      list.shift();
    }
    return this.updateViews();
  },
  contain: function(ice) {
    return this.list.indexOf(ice) >= 0;
  },
  containById: function(id) {
    return this.contain(iceModel.findById(id));
  },
  getIce: function() {
    return this.list;
  },
  updateViews: function() {
    updateSelection();
    return updateIceList();
  }
};

/*
  view
*/


updateSelection = function() {
  return $('#icecream-list').text($.map(selectionModel.getIce(), function(val) {
    return val.name;
  }).join(" > "));
};

updateIceList = function() {
  var i, _i, _len, _ref, _results;
  $('.selected').removeClass("selected");
  _ref = selectionModel.list;
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    if ($('#' + i.id).hasClass("selected")) {

    } else {
      _results.push($('#' + i.id).addClass("selected"));
    }
  }
  return _results;
};

$(function() {
  var els;
  els = $('#icecreams');
  return $.each(iceModel.getAll(), function(i, icecream) {
    return els.append($("<li>").attr('id', icecream.id).append($("<span>").text(icecream.name)).click(function(event) {
      return onclickIce(event);
    }));
  });
});

/*
  Controller
*/


onclickIce = function(event) {
  var icecream;
  icecream = $(event.currentTarget).attr('id');
  if (icecream) {
    return selectionModel.add(iceModel.findById(icecream));
  }
};

/*
  Modelテスト
*/


ok = function(title, expect, value) {
  if (expect === value) {
    return console.log("OK : " + title);
  } else {
    return console.log("NG : " + title + " [" + expect + "] --> [" + value + "]");
  }
};

testModels = function() {
  var all;
  all = iceModel.getAll();
  ok("iceModel:個数", all.length, 6);
  ok("iceModel.findById", iceModel.findById("t4"), all[3]);
  ok("selectionModel:最初の個数", selectionModel.getIce().length, 0);
  ok("selectionModel.contain:空の場合", false, selectionModel.contain(all[0]));
  selectionModel.add(all[0]);
  ok("selectionModel.contain:1つめを追加した時の個数", selectionModel.getIce().length, 1);
  ok("selectionModel.contain:1つめを追加した時のチェック", true, selectionModel.contain(all[0]));
  selectionModel.add(all[1]);
  ok("selectionModel.contain:2つめを追加した時の個数", selectionModel.getIce().length, 2);
  ok("selectionModel.contain:2つめを追加した時のチェック", true, selectionModel.contain(all[1]));
  selectionModel.add(all[2]);
  ok("selectionModel:3つめを追加した場合の", selectionModel.getIce().length, 2);
  ok("selectionModel.contain:3つめを追加した時のチェック", true, selectionModel.contain(all[2]));
  return ok("selectionModel.contain:3つめを追加した時の個数", false, selectionModel.contain(all[0]));
};

testModels();
